name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run: dotnet test
