name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Test
      run: dotnet test
